---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 蓝色幻想.
--- DateTime: 2021/2/15 17:30
---

local UIBase = BaseClass("UIBase")

function UIBase:__init()

end

function UIBase:Load()

end

return UIBase