---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by clkchen.
--- DateTime: 2021/3/11 11:33
---

UILayer =
{
    MainLayer = 1,
    FunctionLayer = 2,
    TipLayer = 3,
    TopLayer = 4,
    DeactiveLayer = 5,
}