---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 蓝色幻想.
--- DateTime: 2021/2/16 1:18
---

local TestCtrl = BaseClass("TestCtrl", UIBase)
local base = UIBase

function TestCtrl:ctor()
    base:ctor(UILayer.MainLayer)
    print("TestCtrl初始化")
end

return TestCtrl