// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TestEnum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from TestEnum.proto</summary>
public static partial class TestEnumReflection {

  #region Descriptor
  /// <summary>File descriptor for TestEnum.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static TestEnumReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5UZXN0RW51bS5wcm90byo0CgVFVHlwZRINCglUZXN0VHlwZTEQABINCglU",
          "ZXN0VHlwZTIQARINCglUZXN0VHlwZTMQAmIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EType), }, null, null));
  }
  #endregion

}
#region Enums
public enum EType {
  [pbr::OriginalName("TestType1")] TestType1 = 0,
  [pbr::OriginalName("TestType2")] TestType2 = 1,
  [pbr::OriginalName("TestType3")] TestType3 = 2,
}

#endregion


#endregion Designer generated code
